"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import styles from "../../auth.module.css";

interface MfaEnrollClientProps {
  nextPath: string;
}

interface EnrollmentState {
  factorId: string;
  qrCode: string;
  secret: string;
}

export default function MfaEnrollClient({
  nextPath,
}: MfaEnrollClientProps) {
  const router = useRouter();
  const [enrollment, setEnrollment] = useState<EnrollmentState | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);

  async function beginEnrollment() {
    setError("");
    setBusy(true);

    try {
      const supabase = createSupabaseBrowserClient();
      const { data: factors, error: factorsError } =
        await supabase.auth.mfa.listFactors();

      if (factorsError) {
        throw factorsError;
      }

      const verifiedFactor = factors.totp.find(
        (factor) => factor.status === "verified",
      );

      if (verifiedFactor) {
        router.replace(
          `/auth/mfa/challenge?next=${encodeURIComponent(nextPath)}`,
        );
        return;
      }

      const unverifiedFactors = factors.totp.filter(
        (factor) => factor.status === "unverified",
      );

      for (const factor of unverifiedFactors) {
        await supabase.auth.mfa.unenroll({ factorId: factor.id });
      }

      const { data, error: enrollError } = await supabase.auth.mfa.enroll({
        factorType: "totp",
      });

      if (enrollError) {
        throw enrollError;
      }

      setEnrollment({
        factorId: data.id,
        qrCode: data.totp.qr_code,
        secret: data.totp.secret,
      });
    } catch (enrollmentError) {
      setError(
        enrollmentError instanceof Error
          ? enrollmentError.message
          : "The authenticator setup could not begin.",
      );
    } finally {
      setBusy(false);
    }
  }

  async function verifyEnrollment(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");

    if (!enrollment || code.trim().length < 6) {
      setError("Enter the current six-digit code from your authenticator app.");
      return;
    }

    setBusy(true);

    try {
      const supabase = createSupabaseBrowserClient();
      const { data: challenge, error: challengeError } =
        await supabase.auth.mfa.challenge({
          factorId: enrollment.factorId,
        });

      if (challengeError) {
        throw challengeError;
      }

      const { error: verifyError } = await supabase.auth.mfa.verify({
        factorId: enrollment.factorId,
        challengeId: challenge.id,
        code: code.trim(),
      });

      if (verifyError) {
        throw verifyError;
      }

      const response = await fetch("/api/auth/mfa/complete", {
        method: "POST",
      });

      if (!response.ok) {
        throw new Error("The MFA enrollment could not be recorded.");
      }

      router.replace(nextPath);
      router.refresh();
    } catch (verificationError) {
      setError(
        verificationError instanceof Error
          ? verificationError.message
          : "The authenticator code could not be verified.",
      );
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className={styles.card}>
      <p className={styles.eyebrow}>AUTHENTICATOR ENROLLMENT</p>
      <h1>Protect your account.</h1>
      <p>
        Every purchaser must use a time-based security code generated by an
        authenticator app. The code changes approximately every 30 seconds.
      </p>

      {error ? <p className={styles.error}>{error}</p> : null}

      {!enrollment ? (
        <div className={styles.actions}>
          <button
            className={styles.button}
            type="button"
            onClick={beginEnrollment}
            disabled={busy}
          >
            {busy ? "Preparing…" : "Generate security key"}
          </button>
        </div>
      ) : (
        <form className={styles.form} onSubmit={verifyEnrollment}>
          <div className={styles.qrPanel}>
            <img
              className={styles.qrImage}
              src={enrollment.qrCode}
              alt="QR code for La Grandiosa authenticator enrollment"
            />

            <p className={styles.helper}>
              Scan the QR code with your authenticator app. If scanning is not
              available, enter this security key manually:
            </p>

            <code className={styles.secret}>{enrollment.secret}</code>
          </div>

          <label className={styles.field}>
            <span>Current six-digit authenticator code</span>
            <input
              value={code}
              onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))}
              type="text"
              inputMode="numeric"
              autoComplete="one-time-code"
              minLength={6}
              maxLength={8}
              required
            />
          </label>

          <button className={styles.button} type="submit" disabled={busy}>
            {busy ? "Verifying…" : "Enable authenticator"}
          </button>
        </form>
      )}
    </section>
  );
}
